### ISSUE TITLE
what does the overpass query on notes do?

### ISSUE THREAD

**Issue by joshinils** [OSM-de/osm-org-greasemonkey#1]
maybe add a mouse-over text via `title="explanation"` on the element with the link
https://github.com/OSM-de/osm-org-greasemonkey/blob/44f49215b6d43f690a3d334e0c34701f62708007/osm-org-greasemonkey.user.js#L173
```js 
anchor.innerHTML = "<center title=\"explanation\">" + text + "</center>";
``` 
(with correct js quote escaping)

**Comment by kmpoppe** [comment]
Resolved with 4d154c6 (Release 0.14, Version 14 of the script)

Used `anchor.title` instead of changing the `innerHTML`, but works all the same.
