### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kmpoppe** [OSM-de/osm-org-greasemonkey#13]
3) Update README.md with a screenshots so that people can see what exactly this script adds.

_Originally posted by @mxxcon in https://github.com/OSM-de/osm-org-greasemonkey/issues/11#issuecomment-1229346891_

**Comment by joshinils** [comment]
Not necessarily screenshots of everything, but I vote for a complete list.

**Comment by kmpoppe** [comment]
Sure.
