### ISSUE TITLE
notes changes do not work, because of missing sidebar on notes page

### ISSUE THREAD

**Issue by joshinils** [OSM-de/osm-org-greasemonkey#17]
```
TypeError: document.getElementById(...) is null sandbox eval code:39:12
    onload user-script:https://github.com/OSM-de/osm-org-greasemonkey/Additional Links for the openstreetmap.org-sidebar:39
    (Async: EventHandlerNonNull)
    userScript user-script:https://github.com/OSM-de/osm-org-greasemonkey/Additional Links for the openstreetmap.org-sidebar:18
    scopeWrapper user-script:https://github.com/OSM-de/osm-org-greasemonkey/Additional Links for the openstreetmap.org-sidebar:501
    <anonymous> user-script:https://github.com/OSM-de/osm-org-greasemonkey/Additional Links for the openstreetmap.org-sidebar:502
    inject resource://gre/modules/ExtensionContent.jsm:595
    AsyncFunctionNext self-hosted:810
```

https://github.com/OSM-de/osm-org-greasemonkey/blob/877e36b1330c44358bfc07a097dac9a233ffbc19/osm-org-greasemonkey.user.js#L38-L50

**Comment by kmpoppe** [comment]
What exactly do you mean? I believe, as I wrote in 2022c12, that clicking on a new note without moving the map will not trigger the observer and thus it won't read the new information about the note.

**Comment by joshinils** [comment]
Oh right, I missed relevant context when writing this.

I'm talking about;
https://www.openstreetmap.org/user/cyton/notes

there is no sidebar, so `document.getElementById("sidebar").style.cssText = `  generates an error and the button to filter for only open notes does not appear

**Comment by kmpoppe** [comment]
Ah! That's a totally different area, and yes there's no sidebar there... Will fix :)
