### ISSUE TITLE
with version 13 the streetlevel imagery buttons do not appear

### ISSUE THREAD

**Issue by joshinils** [OSM-de/osm-org-greasemonkey#2]
only 
with a way open, 
a node open,
a note open,
user history open
a changeset open
a relation open

**Comment by kmpoppe** [comment]
Resolved with 4d154c6 (Release 0.14, Version 14 of the script)

I managed to do educated guesses via the OSM API as to the centroid of the object shown when there is no "map=" in the URL.

**Comment by joshinils** [comment]
hm, no not for me.

when i reload the page, the buttons in the navbar disappear.
https://www.openstreetmap.org/#map=19/52.63382/13.29129

logging the following objects results in:
```
objectMatches null
mapMatches Array(4) [ "#map=19/52.63382/13.29129", "19", "52.63382", "13.29129" ]
sidebar_content undefined
navbar_content undefined
```

so the code in the if-statements never executes and never adds the buttons

**Comment by kmpoppe** [comment]
See #9
