### ISSUE TITLE
hide resolved notes on user pages

### ISSUE THREAD

**Issue by joshinils** [OSM-de/osm-org-greasemonkey#4]
https://www.openstreetmap.org/user/cyton/notes
may contain open and closed notes, I think it be better if I can hide closed notes via some checkmark on that site.

* pagination does not know, so if all are closed on page n go to page n+1,
  * somehow change pagination to allow going back two or more pages, otherise going back is impossible and always leads to redirects
* if a page number is too large, go to page 1?
  * may lead to infinite redirect loop, maybe a link to page 1 or prev. page number would be better

**Comment by joshinils** [comment]
also some colors are always good, like highlighting my username, so i can distinguish notes i created from notes i commented on.

mine are marked with css class `creator` so filtering via css is possible here
```
html body.notes.notes-index.vsc-initialized div#content div.content-body div.content-inner table.table.table-sm.note_list tbody tr.creator
{background: white}

html body.notes.notes-index.vsc-initialized div#content div.content-body div.content-inner table.table.table-sm.note_list tbody tr
{background: lightgray}
```

**Comment by kmpoppe** [comment]
I've been thinking about this as well ;)

There are two options: 

Either cope with what gets delivered from the server, do some educated guessing on whether a page should be skipped and have pages with only one entry. Not favourable.

Alternatively, we could use the OSM API to pull the open notes (`https://api.openstreetmap.org/api/0.6/notes/search.json?display_name=<URL encode user's Display Name>&closed=0`), throw away the complete contents of what comes from the server, fill with what comes from API and also overtake the `content-inner`-div >> `p` that displays the pagination and rebuild all the links. Favourable option, although lots more work.

Your take on that, @joshinils?

**Comment by kmpoppe** [comment]
Decided to take the full option. Version 15, Release 0.15

**Comment by joshinils** [comment]
the header of the table is also gone now, which contained 

  | Id | Creator | Description | Created at | Last changed
-- | -- | -- | -- | -- | --

and there is no clickable way to go back to the previous look, at least not without reloading the whole page.
and at that point the button to only show open notes is not needed, since only open notes are shown.
