### ISSUE TITLE
make open notes sortable

### ISSUE THREAD

**Issue by joshinils** [OSM-de/osm-org-greasemonkey#6]
i.e. sort open notes ascending/descending by date  of "Created at" or "Last changed"

**Comment by kmpoppe** [comment]
Once I re-added the table header (#10, doh!), I could make that work using jQuery, even though I hate using stupidly over-powered frameworks with a burning passion ;-)

**Comment by joshinils** [comment]
oh, you don't want to implement a sort function by yourself? /s
