### ISSUE TITLE
hotkeys for tile-layers

### ISSUE THREAD

**Issue by joshinils** [OSM-de/osm-org-greasemonkey#7]
i.e. pressing 1 changes to carto, pressing 2 changes to cyclosm, 4 to cycle map etc. in the list of available map layers.

**Comment by joshinils** [comment]
alt + number switches tabs in firefox.
so if the open tab is not the only tab open in the window this won't work. but it does switch layers before switching tabs away.

the only problem seems to be that switching sometimes works and sometimes doesn't.

for example switching 1,2,1,2,1,2 goes to layers 1,2,1,1,1,2
but 1,2,3,1,2,3,1,2,3 works correctly

**Comment by kmpoppe** [comment]
My Firefox doesn't switch Tabs using alt + numbers. Is this a standard setting that my machine doesn't have for any particular reason?

**Comment by joshinils** [comment]
> My Firefox doesn't switch Tabs using alt + numbers. Is this a standard setting that my machine doesn't have for any particular reason?

oh, i guess on windoe it is ctrl + number, on linux it is alt + number, ffs :roll_eyes:
